name: AI Test Agent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  agent-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run AI Agent
        run: npm run agent

      - name: Upload Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: agent-dashboard
          path: agent-report.html
